# NumPy

NumPy is a Python library used for working with arrays, and it stands for Numerical Python

Advantages:
- NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.
- better runtime

In [1]:
import numpy as np

In [2]:
arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [3]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)

[[1 2 3]
 [4 5 6]]


In [4]:
arr = np.array([1, 2, 3], dtype=str)

print(arr)

['1' '2' '3']


In [5]:
len(arr)

3

In [6]:
# 3D array
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [7]:
arr = np.array([1, 2, 3, 4], ndmin=3)

print(arr)
print('number of dimensions :', arr.ndim)

[[[1 2 3 4]]]
number of dimensions : 3


### Indexing Arrays

In [8]:
arr = np.array([1, 2, 3, 4])

print(arr[0])

1


In [12]:
arr = np.array([[[1, 2, 3], [0, 0, 0]], [[1, 2, 3], [5, 5, 5]]])

print(arr[1])

[[1 2 3]
 [5 5 5]]


In [28]:
arr = np.array([[[1, 2, 3], [0, 0, 0]], [[1, 2, 3], [5, 5, 5]]])

print(arr[1][1][1])
print(arr[0, 1])

5
[0 0 0]


In [29]:
arr = np.array([[[1, 2, 3], [0, 0, 0]], [[1, 2, 3], [5, 5, 5]]])

arr[0, 1] = [3,3,3]
arr

array([[[1, 2, 3],
        [3, 3, 3]],

       [[1, 2, 3],
        [5, 5, 5]]])

In [13]:
arr = np.array([1, 2, 3, 4])

print(arr[2] + arr[3])

7


### Array Slicing

In [14]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[4:])

[5 6 7]


### Reshaping arrays

In [15]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [16]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(2, 2, -1)

print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


#### Convert the array into a 1D array

In [17]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

newarr = arr.reshape(-1)

print(newarr)

[1 2 3 4 5 6]


### Numpy Zeros and Ones

In [30]:
np.zeros((3,3,), dtype="int32")

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [31]:
np.ones((3,3,), dtype="int32")

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int32)

In [32]:
np.full((3,3), 10, dtype="float64")

array([[10., 10., 10.],
       [10., 10., 10.],
       [10., 10., 10.]])

In [33]:
np.random.rand(3,3)

array([[0.05845451, 0.76501788, 0.40689638],
       [0.49034152, 0.41561308, 0.60991861],
       [0.65322352, 0.38245167, 0.89070635]])

In [35]:
np.random.randint(1,6, size = (3,3))

array([[2, 4, 5],
       [2, 4, 3],
       [3, 1, 4]])

In [36]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Numpy Operations

In [37]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

arr + 1

array([[2, 3, 4],
       [5, 6, 7]])

In [38]:
arr.mean()

np.float64(3.5)